### ISSUE TITLE
Having an example org file

### ISSUE THREAD

**Issue by mssola** [frankjonen/emacs-for-writers#2]
First of all, great work! It looks really nice. I also worked on something similar some months ago (https://github.com/mssola/writer-mode) but then I ended up abandoning it in favor of scrivener (mainly because I needed something ready right now and my knowledge of org-mode was not optimal). After using this I see that I might had been over-complicating things (e.g. automatically fitting the size for the outline). So, whenever I start back I may use some of your ideas.

Anyways, as I said, I'm not that experienced with org-mode, and one thing that I struggled with and that scrivener does really well is exporting into a pdf, odt, etc. I know that org-mode also has that, but I got lost really fast with all the myriad of options, tags, etc. So I guess that what I'm asking is: could you post an example org file? And with it the org tags, headers, etc. that you are using on a real project (e.g. title, export options, document header, etc.). The contents don't have to be real (it can be a lorem ipsum for all I care). Also, from the example gif I see that you are setting something under each section (highlighted in cyan blue). Are those org-specific settings as well? In the end, what I'm asking, I guess, is a way to see how a real user would use it, and test the workflow myself.

On another note, I see that you are using global notes. In scrivener, for example, you can have notes and comments for each specific file (a file there corresponds to a chapter, so I guess that in this context it would be the equivalent of a section here?). Is there a way to implement something similar with this setup? Or you are only relying on a global file on your day-to-day usage?

Thanks!

**Comment by frankjonen** [comment]
Thank you. I used Scrivener a lot for quite a few years since when it came out. I still have a bunch of `.scriv` Rich Text bundles that I have to convert at some point. One of the reason I'm never going back to systems like that. 

Looking at your minor mode setup, it's pretty cool to have something that can be called into any major mode buffer. 

Yes, I'll put together a sample org file setup demoing some of the features (demoing all of `org-mode` would be madness). I think I'll use parts of Moby Dick again like in [this example](https://gfycat.com/friendlyheartfeltcrane). The teal squiggly lines are just sub-headings. It's from a project documentation. Right now <kbd>F7</kbd> export a HTML document. For a next version I'll untangle my PDF export setup and map that to a key as well. Either the next or the one after that. I rather have many little updates than "feature packed" big ones.

As for implementing the notes: Nah, not with this setup. I'll actually have to think about how to do that in a managed way that I'll actually want to use every day. I found that if it's too "managed" it becomes a burden to use. If it's a little messy it's more inviting to just scrap things out.

In this initial version I haven't given the notes feature much thought to be honest. My notes setup is simple. It's a general idea capture mechanism where I scrap things out before and refine them in the main outline (I was a tad excessive in Scrivener with notes, so part of this is me stepping on the brakes). In my personal setup the notes file of each project is in a sym-linked iCloud folder, so I can jot down things on the go in [iA Writer](https://ia.net/writer) (a large part of the reason behind keeping the notes in Markdown). Eventually I want to have like a `[chapter,section,custom]*.*` kind of thing, maybe (quite likely) as a folder setup for sanitary reasons. That way all of the notes files would be in the corresponding folder of the chapter/section/custom `.org` file. It should also be easy for others to modify to the structures *they* want.

Let's just say I have a big wish-list of what I want this to do.
